### ISSUE TITLE
@connection doesn't work on interface properties

### ISSUE THREAD

**Issue by EloB** [taylorgoolsby/graphql-directive-connection#14]
I'm not sure how it should work but it would be nice if it worked :)

**Comment by taylorgoolsby** [comment]
I don't use interfaces. Can you post vanilla GraphQL code of your use case?

**Comment by EloB** [comment]
I changed line to `d.kind === 'ObjectTypeDefinition' || d.kind === 'InterfaceTypeDefinition'` and that worked.
https://github.com/taylorgoolsby/graphql-directive-connection/blob/master/src/applyConnectionTransform.ts#L232

**Comment by EloB** [comment]
```graphql
type Thing {
  # ...
}

interface Some {
  things: Thing @connection
}

type My {
  things: Thing @connection
}
```

**Will output**

```graphql
type Thing {
  # ...
}

interface Some {
  things: Thing
}

type My {
  things: ThingConnection
}
```

**Expected output**

```graphql
type Thing {
  # ...
}

interface Some {
  things: ThingConnection
}

type My {
  things: ThingConnection
}
```

**Comment by EloB** [comment]
#15

**Comment by taylorgoolsby** [comment]
Ah I see now. Thank you for the PR! I'll set a reminder for later today to try and get that unit test working and merge.

**Comment by EloB** [comment]
@taylorgoolsby Any progress on this mate? :)

I'm a bit blocked by this... <3

**Comment by taylorgoolsby** [comment]
Deployed to 1.5.0
