### ISSUE TITLE
Add totalCount field to Connection type

### ISSUE THREAD

**Issue by Yunoo** [taylorgoolsby/graphql-directive-connection#3]
Currently, the `Connection` type is missing a `totalCount` field. 
[The relay cursor connection specification](https://facebook.github.io/relay/graphql/connections.htm) has not specified the `totalCount` field to be part of the `Connection` type while [graphql.org](https://graphql.org/learn/pagination/#end-of-list-counts-and-connections) suggests having this field in place.

I think this field enables the client to get additional data about the paginated data, which could be beneficial to have. I suggest adding this field and making it nullable in case an arbitrary pagination implementation does not provide the total amount of results.

**Comment by taylorgoolsby** [comment]
@Yunoo fixed and published
